app/models/brand.rb, app/models/ingredient.rb, app/models/ingredient_review.rb, app/models/product.rb, app/models/product_ingredient.rb, app/models/product_review.rb, app/models/user.rb, db/migrate/20201130062509_create_brands.rb, db/migrate/20201130063022_create_products.rb, db/migrate/20201130063228_create_ingredients.rb, db/migrate/20201130063305_create_product_ingredients.rb, db/migrate/20201130063508_create_ingredient_reviews.rb, db/migrate/20201130063548_create_product_reviews.rb, db/schema.rb, test/models/brand_test.rb, test/models/ingredient_review_test.rb, test/models/ingredient_test.rb, test/models/product_ingredient_test.rb, test/models/product_review_test.rb, test/models/product_test.rb
Following models have been created:
User
Ingredient
Product
Brand
Product_ingredients
product_reviews
ingredient_review
=> ARCH:initial models created

app/controllers/brands_controller.rb, app/controllers/ingredient_reviews_controller.rb, app/controllers/ingredients_controller.rb, app/controllers/product_ingredients_controller.rb, app/controllers/product_reviews_controller.rb, app/controllers/products_controller.rb, app/controllers/users_controller.rb, test/controllers/brands_controller_test.rb, test/controllers/ingredient_reviews_controller_test.rb, test/controllers/ingredients_controller_test.rb, test/controllers/product_ingredients_controller_test.rb, test/controllers/product_reviews_controller_test.rb, test/controllers/products_controller_test.rb, test/controllers/users_controller_test.rb
Generated skeleton controllers for application
=> ARCH: generated basic controllers

config/routes.rb
added basic routes for products and ingredients
=> added basic routes for products and ingredients

db/migrate/20201130055326_devise_create_users.rb, db/schema.rb, db/seeds.rb
Very basic seeds are done, guys!
User1 is our certified user.
All ingredient reviews are tied to User1.
=> ARCH: basic seeds for testing

app/controllers/ingredients_controller.rb, app/views/ingredients/show.html.erb, config/routes.rb
Individual show page for ingredients is working. 
Controller::show created and working 
Ingredient and ingredient review tables linked.
=> ARCH: individual show page for ingredient up

app/models/brand.rb, app/models/ingredient.rb, app/models/ingredient_review.rb, app/models/product.rb, app/models/product_review.rb, app/models/user.rb, app/views/ingredients/show.html.erb, db/seeds.rb
Validations added for user:
Each user must have a username, email, password, first_name, last_name, age and gender.
Username and email must be unique.
Gender must be included in list provided.
Users can add a photo to their profile.
Seeds file changed so that all instances from each class match the validations. please run a db:seed:replant before using the code.
=> ARCH: validations for user added

app/controllers/ingredient_reviews_controller.rb, app/controllers/ingredients_controller.rb, app/models/ingredient.rb, app/models/ingredient_review.rb, app/models/product_review.rb, app/models/user.rb, app/views/ingredient_reviews/_form.html.erb, app/views/ingredients/show.html.erb, config/routes.rb, db/migrate/20201130063548_create_product_reviews.rb, db/migrate/20201202035309_add_skin_type_to_users.rb, db/migrate/20201202041540_add_recommended_to_product_reviews.rb, db/migrate/20201202060921_add_skin_concern_to_product_reviews.rb, db/migrate/20201202062712_add_skin_concern_to_ingredient_reviews.rb, db/schema.rb, db/seeds.rb
Migrations created for user, product reviews and ingredient reviews.
Added "skin type" column to user. 
Added "recommend:boolean" and "skin concern" columns to product review
Added "skin concern" column to ingredient review
Seeds altered to meet validations for new migrations.
"Create" and "Index" method added to Ingredient review controller 
Simple form for Ingredient review creation added to individual ingredient show page. Alarm is displayed if review is not valid.
=> Migrations

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/ingredients_controller.rb, app/controllers/pages_controller.rb, app/controllers/products_controller.rb, app/models/ingredient.rb, app/models/product.rb, app/views/ingredients/index.html.erb, app/views/ingredients/show.html.erb, app/views/products/index.html.erb, app/views/shared/_ingredientsearchbarform.html.erb, app/views/shared/_productsearchbarform.html.erb, db/schema.rb
Hi guys, i upgraded our search sophistication for ingredients and products and added some navigation buttons
=> Upgrading product search

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_products_index.scss, app/views/products/index.html.erb
updated product page to make room for tag filter elements
=> updating product page placeholder for filters/tags

app/models/ingredient.rb, app/services/scraper.rb, db/schema.rb
removed validations that were blocking seeds from working
=> removing a validation that was stopping seeds from working

app/views/products/index.html.erb, app/views/products/show.html.erb
added images to product and show pages
from the img columns in the products table
=> added images from Product instances to index and show pages

app/assets/stylesheets/components/_avatar.scss, app/models/product.rb, app/views/shared/_navbar.html.erb
added logo and user pic to navbar, redirect to home from logo click and adjusted search settings to incorporate category, sub-category, oneliner and removed dependency on brand description
=> Tweaks to navbar and search logic

app/controllers/products_controller.rb, app/models/product.rb, app/views/products/show.html.erb
Test cases 
If there are not ingredients, this works
Took into account if there are ingredients but they dont have average safety rating
Also took into account if one ingredient has a rating but the other one doesn't, previously it was showing 0
Added ingredients on show page of the products
=> fixed + added ingredients on show page

app/controllers/products_controller.rb, app/services/scraper.rb, config/routes.rb
=> fixed scraper ingredients to products

app/models/product.rb, app/services/inci_scraper.rb, db/migrate/20201204052253_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
=> FIX: simplified seed for heroku

Gemfile.lock, app/models/brand.rb, app/models/product.rb, db/schema.rb, db/seeds.rb
- reverted most changes from the basic seed switch :) 
- left the .delete_all at the seed to remove any duplicates
=> FIX: switched back to scraper seed

db/seeds.rb
redid seeds so we have a cohesive story,
=> updated seeds for coelaic user story

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_text.scss, app/assets/stylesheets/pages/_ingredient_show.scss, app/assets/stylesheets/pages/_ingredients_index.scss, app/assets/stylesheets/pages/_searchbars.scss, app/views/ingredients/index.html.erb, app/views/ingredients/show.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/shared/_ingredientsearchbarform.html.erb, app/views/shared/_navbar.html.erb
Made some final structural changes for the designs in the ingredients index and show pages, and made some tweaks to the nav bar
=> Design monday kelso

app/views/products/show.html.erb
Favorite button shows up if the current user hasn't favorited the product.
If product is already favorited, unfavorite button is displayed
You can't favorite something, if not signed in
=> Favorite fix

app/views/ingredients/show.html.erb, app/views/products/show.html.erb, app/views/shared/_navbar.html.erb
adjusted navbar, show pages for ingredients and products to display user images and names properly
=> Avatar and Name fixes

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/pages/_product_show.scss, app/javascript/channels/_modal.js, app/views/products/show.html.erb
added popup review functionality
edited the avatars display and moved into avatar component
=> Popup Review Functionality

app/controllers/ingredients_controller.rb, app/views/products/show.html.erb, db/seeds.rb
added description to our demo ingredients from seeds
changed all ingredients to link to ingredient show page from product show page
=> Seed changes ingredients description and linking

app/views/shared/_filterform.html.erb, db/seeds.rb
added tags to products in seeds
removed some excess tags and corrected tag spelling
=> Adding Tags to Products

app/controllers/products_controller.rb, app/views/products/index.html.erb, db/seeds.rb
Pagination fixed so it doesnt show when search is being conducted on index
=> pagination fixed

app/assets/stylesheets/components/_navbar.scss, app/controllers/users_controller.rb, app/views/shared/_navbar.html.erb, app/views/users/favorites.html.erb, config/routes.rb
added a favorites index page
adjusted routes and routing of links
=> Products Favorited Index Page

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_searchbars.scss, app/views/pages/home.html.erb, app/views/shared/_productsearchbarform.html.erb
fixed up home page to be more in-line with figma
fixed up shared navbar
=> Home Page Front End

app/models/product_search.rb, app/views/products/index.html.erb, app/views/shared/_filterform.html.erb
search and filter bugs are fixed
=> fixed filter and search bugs

app/views/products/_products.html.erb
removed extra </div> and end tags that were breaking the index
=> Fixing Product Index Page

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_ingredient_show.scss, app/views/ingredients/show.html.erb
added carousel and maded some structural changes to the ingredients show page
=> Carousel baby

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/config/_application.scss, app/assets/stylesheets/pages/_breadcrumbs.scss, app/assets/stylesheets/pages/_footers.scss, app/assets/stylesheets/pages/_prod-show.scss, app/assets/stylesheets/pages/_product_show.scss, app/assets/stylesheets/pages/_products_index.scss, app/assets/stylesheets/pages/_searchbars.scss, app/views/ingredients/index.html.erb, app/views/ingredients/show.html.erb, app/views/layouts/application.html.erb, app/views/products/_products.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/shared/_footers.html.erb, app/views/shared/_ingredientsearchbarform.html.erb, app/views/shared/_productsearchbarform.html.erb
adjusted product filter bar
adjusted search bars to include links
added footer and made it sticky
adjusted buttons on various pages to match design philosophy
color corrected breadcrumbs
=> CSS changes to product index and ingredients index

app/views/products/show.html.erb
changed ingredients display from list to 3 columns in a row
=> CSS changes to ingredients display in product show page

app/assets/stylesheets/pages/_ingredient_show.scss, app/models/ingredient.rb, app/views/ingredients/show.html.erb, app/views/products/_product.html.erb, app/views/products/_products.html.erb
The style is all shit but we've got a good template to fix up tomorrow
=> Alternative product recommendations

app/views/ingredients/show.html.erb, app/views/users/favorites.html.erb
added ingredient review sources to global popular resources list
=> Ingredient show page tweaks

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_breadcrumbs.scss, app/controllers/ingredients_controller.rb, app/controllers/products_controller.rb, app/views/shared/_breadcrumbs.html.erb, app/views/shared/_navbar.html.erb
=> navbar elements centered and breadcrumbs style sorter

app/assets/stylesheets/pages/_ingredient_show.scss, app/views/ingredients/show.html.erb
changed font color for product carousel header and content
=> changed font color for product carousel header and content

Gemfile, Gemfile.lock, app/models/ingredient_review.rb, db/seeds.rb
populated products and ingredients with reviews from seedfile
=> populated products and ingredients with reviews from seedfile

app/controllers/users_controller.rb, app/views/users/favorites.html.erb
=> working favorite show page

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/config/_text.scss, app/assets/stylesheets/pages/_prod-show.scss, app/assets/stylesheets/pages/_product_show.scss, app/views/ingredients/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/products/show.html.erb
=> product show page and some other design components

app/controllers/favorites_controller.rb, app/views/products/show.html.erb, app/views/shared/_progresscircle.html.erb, config/routes.rb, test/controllers/favorites_controller_test.rb
Changed the routes for favorites
Added a new controller
Changed the paths 
Created new methods
Changed the paths for redirection
=> Fix favorites

app/assets/stylesheets/pages/_product_show.scss, app/views/products/show.html.erb
moved heart to top right, and deleted excess heart logic
=> Removing dupe heart

app/assets/stylesheets/config/_text.scss, app/views/shared/_productsearchbarform.html.erb
removed view all products button from home page
added color change to link hover
resized ingredient page to fit each ingredient on one line (id:25 and id:35)
=> Front end fixes per LeWagon recommendations

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_ingredient_show.scss, app/assets/stylesheets/pages/_product_show.scss, app/assets/stylesheets/pages/_products_index.scss, app/views/ingredients/index.html.erb, app/views/ingredients/show.html.erb, app/views/products/_product.html.erb, app/views/products/_products.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/shared/_filterform.html.erb, app/views/shared/_footers.html.erb
basically did minor design tweaks for most components and layouts and pages all over the shop. 
I get that it looks like i did a lot. Happy to run you through how everything looks firtst thing xo
See y'all tomorrow boys xoxo
=> fixed up design tweaks all over the shop

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_progress.scss, app/assets/stylesheets/pages/_ingredient_show.scss, app/assets/stylesheets/pages/_ingredients_index.scss, app/assets/stylesheets/pages/_products_index.scss, app/views/ingredients/index.html.erb, app/views/ingredients/show.html.erb, app/views/shared/_progresscircle.html.erb
=> front end tweaks

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_prod-show.scss, app/assets/stylesheets/pages/_product_show.scss, app/assets/stylesheets/pages/_products_index.scss, app/views/ingredients/show.html.erb, app/views/shared/_filterform.html.erb, app/views/users/favorites.html.erb, config/meta.yml
All changes have been made. App is looking great.
=> final front-end tweaks

app/views/ingredients/show.html.erb
added if statement to js script ingredient show page to prevent errors due to unverified user
=> added if statement to js script ingredient show
